build:
  image: ciscocloud/mantl
  environment:
    GOOGLE_ACCOUNT_FILE: "$$GOOGLE_ACCOUNT_FILE"
  commands:
    - env
    - ln -s -f $$CI_MATRIX_ANSIBLE_FILE terraform.yml
    - ln -s -f $$CI_MATRIX_TERRAFORM_FILE terraform.tf
    - testing/integration-test.sh

matrix:
  CI_MATRIX_ANSIBLE_FILE:
    - terraform.sample.yml
  CI_MATRIX_TERRAFORM_FILE:
    - testing/gce.tf
