build:
  image: sehqlr/mantl
  environment:
    GOOGLE_CREDENTIALS: "$$GOOGLE_CREDENTIALS"
  commands:
    - ln -s -f $$CI_MATRIX_ANSIBLE_FILE terraform.yml
    - ln -s -f $$CI_MATRIX_TERRAFORM_FILE terraform.tf
    - testing/integration-test.sh

matrix:
  CI_MATRIX_ANSIBLE_FILE:
    - terraform.sample.yml
  CI_MATRIX_TERRAFORM_FILE:
    - testing/gce.tf
