---
glusterfs_version: 3.7.6
glusterfs_minor_version: 3.7
glusterfs_repo: https://download.gluster.org/pub/gluster/glusterfs/{{ glusterfs_minor_version }}/{{ glusterfs_version }}/EPEL.repo/glusterfs-epel.repo
glusterfs_repo_sha256sum: ee06398d5b09d230fa3ffad4995b83089012a426265741c58a70bf587d14613c

glusterfs_mode: client
glusterfs_replication: "{{ groups[glusterfs_server_group] | count }}"
glusterfs_server_group: role=control

# brick storage
glusterfs_brick_mount: /mnt/glusterfs
glusterfs_brick_volume_group: "{{ volume_group_name }}"
glusterfs_brick_volume_name: glusterfs

# refer to lvcreate manmake to accepted size syntax
# 100%FREE mean all space remain from docker volumes
glusterfs_brick_volume_size: "100%FREE"
glusterfs_brick_device: "/dev/{{ volume_group_name }}/{{ glusterfs_brick_volume_name }}"
glusterfs_volume_force: "{% if volume_group_name !='' %}no{% else %}yes{% endif %}"
glusterfs_brick_location: "{% if volume_group_name != '' %}{{ glusterfs_brick_mount }}{% else %}/etc/glusterfs/data{% endif %}"

# docker volume
glusterfs_container_data_name: container-volumes
glusterfs_container_data_mount: /mnt/{{ glusterfs_container_data_name }}
